# Site settings
title: CongoMines
email: webmaster@congomines.org
description: > # CongoMines is an online document library of materials
               relating to the mining sector in the Democratic Republic of the Congo.
               The project is dedicated to increasing transparency and
               extractive industry governance.  It is maintained by the Carter Center.
baseurl: "/guide" # the subpath of your site, e.g. /blog/
url: http://188.166.93.154/ 
# url: "http://congomines.org" # switch when deployed to congomines.org domain
twitter_username: CongoMines
github_username:  CongoMines

collections:
  guides:
    output: true
    permalink: /:path/

# Build settings
markdown: kramdown
